# Generated by Django 5.0.4 on 2024-04-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcast', '0002_initial'),
        ('useractivity', '0001_initial'),
        ('userzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.user'),
        ),
        migrations.AddField(
            model_name='followedchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.channel'),
        ),
        migrations.AddField(
            model_name='followedchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.user'),
        ),
        migrations.AddField(
            model_name='like',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.episode'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.user'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='episodes',
            field=models.ManyToManyField(to='podcast.episode'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.user'),
        ),
    ]
